apiVersion: batch/v1
kind: CronJob
metadata:
  name: software-consumer
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: software-consumer
            image: software-consumer:latest
          restartPolicy: OnFailure
