apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-consumer
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: news-consumer
            image: news-consumer:latest
          restartPolicy: OnFailure
