apiVersion: batch/v1
kind: CronJob
metadata:
  name: twitter-consumer
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: twitter-consumer
            image: twitter-consumer:latest
          restartPolicy: OnFailure
